# Generated by Django 2.2.3 on 2019-07-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodItems', to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
                ('perItemPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itemName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
                ('orderAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orderTime', models.DateTimeField()),
                ('orderState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderstates', to='orders.OrderState')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSizePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsizeprices', to='orders.FoodItem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizeprices', to='orders.ServiceSize')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAddOnPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemaddonprices', to='orders.AddOn')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemprices', to='orders.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAddOnPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cataddonprices', to='orders.AddOn')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryprices', to='orders.Category')),
            ],
        ),
    ]
