# Generated by Django 2.2.3 on 2019-07-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190728_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='categoryName',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='itemSizeName',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='topping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='topping_list',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
