# Generated by Django 2.2.3 on 2019-08-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cims', '0003_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='address',
        ),
    ]
