# Generated by Django 2.2.3 on 2019-08-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cims', '0012_auto_20190807_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='document',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
