# Generated by Django 2.2.3 on 2019-08-07 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cims', '0013_auto_20190807_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicenote',
            name='sender',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
