# Generated by Django 2.2.3 on 2019-08-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cims', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
