# Generated by Django 2.2.3 on 2019-08-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cims', '0007_auto_20190804_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='lastLoginTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupplierCustomerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customersupplier', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suppliercustomer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('supplier', 'customer')},
            },
        ),
    ]
