# Generated by Django 2.2.3 on 2019-08-06 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cims', '0009_auto_20190804_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='document',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cims.Invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicelineitemnote',
            name='createdTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicenote',
            name='createdTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
