# Generated by Django 2.2.3 on 2019-08-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cims', '0011_auto_20190806_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='document',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
