# Generated by Django 2.2.3 on 2019-07-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190727_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('itemCount', models.IntegerField()),
                ('orderAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orderTime', models.DateTimeField()),
                ('orderState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderstates', to='orders.OrderState')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
                ('perItemPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itemName', models.CharField(max_length=64)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='orders.Order')),
            ],
        ),
    ]
