# Generated by Django 2.2.3 on 2019-07-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orderlineitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='ServiceSize',
            new_name='ServingSize',
        ),
    ]
