# Generated by Django 2.2.3 on 2019-07-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190730_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
